export interface IProduct {
  id: number,
  title: string,
  description: string,
  category: string,
  price: number,
  discountPercentage: number,
  rating: number,
  stock: number,
  tags: string[],
  brand: string,
  sku: string,
  weight: number,
  dimensions: {
    width: number,
    height: number,
    depth: number,
  },
  warrantyInformation: string,
  shippingInformation: string,
  availabilityStatus: string,
  images: string[],
  thumbnail: string,
}